// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcu-JxQiKSJmTV-ueGqn7lDh2lYsX7PDg',
    appId: '1:301022096662:web:4923d6f42bc40009f6f437',
    messagingSenderId: '301022096662',
    projectId: 'campus-connect-b2ce6',
    authDomain: 'campus-connect-b2ce6.firebaseapp.com',
    storageBucket: 'campus-connect-b2ce6.firebasestorage.app',
    measurementId: 'G-ZE65WX34CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq7tyQCIYooagReHVRsnAZXk8A_sUe3c0',
    appId: '1:301022096662:android:b1d4fe86f70e5965f6f437',
    messagingSenderId: '301022096662',
    projectId: 'campus-connect-b2ce6',
    storageBucket: 'campus-connect-b2ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYD2rgmFZG8t5Gp4fEwoCLsKaXItZLug',
    appId: '1:301022096662:ios:3d8024eccd868f75f6f437',
    messagingSenderId: '301022096662',
    projectId: 'campus-connect-b2ce6',
    storageBucket: 'campus-connect-b2ce6.firebasestorage.app',
    iosBundleId: 'com.campusconnect.campusConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYD2rgmFZG8t5Gp4fEwoCLsKaXItZLug',
    appId: '1:301022096662:ios:3d8024eccd868f75f6f437',
    messagingSenderId: '301022096662',
    projectId: 'campus-connect-b2ce6',
    storageBucket: 'campus-connect-b2ce6.firebasestorage.app',
    iosBundleId: 'com.campusconnect.campusConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcu-JxQiKSJmTV-ueGqn7lDh2lYsX7PDg',
    appId: '1:301022096662:web:b381c5c12ece463bf6f437',
    messagingSenderId: '301022096662',
    projectId: 'campus-connect-b2ce6',
    authDomain: 'campus-connect-b2ce6.firebaseapp.com',
    storageBucket: 'campus-connect-b2ce6.firebasestorage.app',
    measurementId: 'G-ES6J96BBEH',
  );
}
