import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../../l10n/generated/app_localizations.dart';
import 'core/theme/app_theme.dart';
import 'core/routes/app_router.dart';
import 'core/providers/locale_provider.dart';
import 'package:toastification/toastification.dart';
import 'package:campus_connect_app/chat/view/webrtc_listener.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'core/network/push_notification_service.dart';
import 'core/network/callkit_service.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
    await PushNotificationService.instance.initialize();
    await CallKitService.instance.initialize();

    // Peek at pending call BEFORE runApp so downstream screens can skip
    // the splash delay and show a black overlay instead of the dashboard.
    await CallKitService.checkAndCachePendingCall();
  } catch (e) {
    debugPrint('Firebase not configured yet: $e');
  }

  runApp(const ProviderScope(child: CampusConnectApp()));
}

class CampusConnectApp extends ConsumerWidget {
  const CampusConnectApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goRouter = ref.watch(routerProvider);
    final locale = ref.watch(localeProvider);

    return Consumer(
      builder: (context, ref, child) {
        return ToastificationWrapper(
          child: ScreenUtilInit(
            designSize: const Size(375, 812), // Standard iPhone design size
            minTextAdapt: true,
            splitScreenMode: true,
            builder: (context, child) {
              return MaterialApp.router(
                title: 'CampusConnect',
                theme: AppTheme.lightTheme,
                routerConfig: goRouter,
                debugShowCheckedModeBanner: false,
                locale: locale,
                localizationsDelegates: const [
                  AppLocalizations.delegate,
                  GlobalMaterialLocalizations.delegate,
                  GlobalWidgetsLocalizations.delegate,
                  GlobalCupertinoLocalizations.delegate,
                ],
                builder: (context, child) {
                  return WebRTCListener(child: child!);
                },
                supportedLocales: AppLocalizations.supportedLocales,
              );
            },
          ),
        );
      },
    );
  }
}
